### ISSUE TITLE
Please add a list of variable names in the docs

### ISSUE THREAD

**Issue by ddbuscombe** [gantian127/bmi_dbseabed#2]
All of the examples make use of a single variable name, 'carbonate'. I found the names of the other variables from the source code

https://github.com/gantian127/bmi_dbseabed/blob/9530b7e9d3e9f0d9588ecaf4c2d82755d7fe910f/src/bmi_dbseabed/dbseabed.py#L11

Please add a list of the variables and their description to the docs. The [website ](https://instaar.colorado.edu/~jenkinsc/dbseabed) doesnt seem to contain this information (or if it does, it is hard to find). I think the KMZ probably has this information, but I am not allowed to use KMZ by my employer. Thanks

**Comment by gantian127** [comment]
@dbuscombe-usgs Thanks very much for your feedback! I will add the variable info the in README section of this repo. Also, to check a list of all available variables, there are two ways.

method 1: use python code:
from bmi_dbseabed import DbSeabed
dbseabed = DbSeabed()
dbseabed.data_services

method2: check the list of all variable names in the docs at the section of "parameter settings"
https://bmi-dbseabed.readthedocs.io/en/latest/#parameter-settings

The tutorial notebook also mentioned these two methods. Thank you! https://github.com/gantian127/bmi_dbseabed/blob/master/notebooks/bmi_dbseabed.ipynb

**Comment by ddbuscombe** [comment]
Thanks for that information. I am starting to realize that data is only available for the Gulf of Mexico, is that right? The 'data link's in the docs point to geotiffs that only cover the Gulf of Mexico region, and no data outside the Gulf seems to be available (see my other issue).
